### ISSUE TITLE
an error in 'MyDatabase.Execute(MySelect, "id") '

### ISSUE THREAD

**Issue by xiahui1986** [Beakerboy/VBA-SQL-Library#19]
Dim MyDatabase As SQLDatabase
    Set MyDatabase = Create_SQLDatabase

    Set MySelect = New SQLSelect
    With MySelect
        .Fields = Array("id")
        .Table = "set"

    End With
    
    ID = MyDatabase.Execute(MySelect, "id")

an error in 'MyDatabase.Execute(MySelect, "id") '

I guess in SQLDatabase, the Function Execute is 
       Public Function Execute(oSQL As iSQLQuery, Optional return_column = "")
The first parameter's  type is iSQLQuery ,but MySelect is SQLSelect
And I use excel 2016

**Comment by Beakerboy** [comment]
What is the error that Excel is displaying? The SQLSELECT class implements the iSQLQuery interface, so that is not the problem.  

I’ve made several large changes since you last posted. Try using the add-in instead of the source code files. This will make your spreadsheet cleaner.

**Comment by xiahui1986** [comment]
My excel is chinese ,so error is chinese 
Translate is "Compilation error: byref parameter type does not match"

**Comment by xiahui1986** [comment]
![image](https://user-images.githubusercontent.com/44365840/49381193-5461b780-f74e-11e8-94b4-4f7642231cd3.png)

**Comment by Beakerboy** [comment]
Use the addin and replace
Set MySelect=newSQLSelect
With
Set MySelect = Create_SQLSelect

**Comment by xiahui1986** [comment]
Runtime error 13 type mismatch
![image](https://user-images.githubusercontent.com/44365840/49382251-eec2fa80-f750-11e8-8c74-786e789d31f6.png)
![image](https://user-images.githubusercontent.com/44365840/49382269-fc788000-f750-11e8-99c0-d8e6bb65dbf8.png)

**Comment by xiahui1986** [comment]
Which version is your office?

**Comment by Beakerboy** [comment]
I use Excel 2017. If you are using the addin, make sure you remove all of the older VBA-SQL-Library files from your spreadsheet. When the error pops up, you can trace the error by pressing F8 until you find the line within the library that is causing the error.

**Comment by Beakerboy** [comment]
Are you setting the DSN, username, and password as well? You should have several other lines of code besides what you show above. If you don’t, that’s the problem. Look at the ReadMe file to see what you need to setup the SQLDatabase Object. You can paste more code and remove any sensitive information. What database are you trying to access? Are you using MS SQL Server or something else?

**Comment by Beakerboy** [comment]
Another thing you can try is to make a new .xlsm file with only the files from the testing directory. These contain all the unit tests. If they run, then the addin should work.

**Comment by xiahui1986** [comment]
I use 
Private Function MakeConnectionString() As String
    conn_str = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" & ThisWorkbook.Path & "\exam.accdb ; " & "Jet OLEDB:Database Password=123456; "
    MakeConnectionString = conn_str
End Function
to replace DateBase set 。
I test "Implements" in other file , like:
class Iset:
    Public Sub xx()
    End Sub

Class Myset:
    Implements Iset
    Private Sub Class_Initialize()
    End Sub
    Public Sub Iset_xx()
        Iset_xx = 11
    End Sub

use class Iset:
    Sub test()
        Set t = New Myset
        a = t.xx        # there is error  "Run Time Error 438 - Object Doesn't Support this Property or Method " ,   
    End Sub


Should I  add some Librarys?

**Comment by xiahui1986** [comment]
I use new file for your code , old file I change few codes to avoid error , but now I want to know how to use Implements , try understand VBA's class  for the future project .

**Comment by Beakerboy** [comment]
It looks like you are using different parameters in your connection than my class is allowing. is that correct? the "Implements" call in to tell the compiler that the class is implementing the required functions and properties specified in an "Interface". I don't know what the Iset interface is I can't help you with that. I think you need:
    Dim t as Iset
    Set t = New MySet

 If you need a custom Connection, try this:

"xiahui1986Connection"

    Implements iSQLConnection

    Private ocnt As ADODB.Connection
    Private sDataSource
    
    Private Sub Class_Initialize()
        Set ocnt = New ADODB.Connection
    End Sub

    Public Property Set DataSource(Source as String)
        sDataSource = Source
    End Property

    Public Property Get iSQLConnection_Connection()
        Set iSQLConnection_Connection = ocnt
    End Property

    Public Sub iSQLConnection_OpenConnection()
        ocnt.Open
    End Sub

    Public Sub iSQLConnection_CloseConnection()
        ocnt.Close
    End Sub

    Public Function iSQLConnection_State()
        iSQLConnection_State = ocnt.State
    End Function

    Public Property Let iSQLConnection_ConnectionString(sConnection As String)
        ocnt.ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" & sDataSource " & ";Jet OLEDB:Database Password=123456; "
    End 

Then you can use the library like this:

Dim MyDatabase As SQLDatabase
Dim MyConnection as xiahui1986Connection

Set MyDatabase = Create_SQLDatabase
Set MyConnection = New xiahui1986Connection
MyConnection.Path = ThisWorkbook.Path & "\exam.accdb"
Set MyDatabase.Connection = MyConnection

**Comment by xiahui1986** [comment]
Thank you very much , now I try use vba's class , maybe several days later , I could understand it , just do it .
