### ISSUE TITLE
Tests not Running

### ISSUE THREAD

**Issue by LightMike** [Beakerboy/VBA-SQL-Library#45]
Hello Kevin,
as in your description I created the 
- SQLlib.xlam
- VBAUnitTester.xlam
- created a new xlsm with the 
- SQLUnitTests  Module 
- SQL..Tests Classes
-  referenced: Microsoft ActiveX Data Objects x.x Library", "Microsoft Scripting Runtime", SQLlib, VBAUnittester
- type '=RunTests()' in Cell("A1")

However error: unknown userdefinded type 'SQLlibTests'
'Dim SQLLibTestConfig As New SQLlibTests'

I cannot find a class named like this. Any idea.
Thanks for your support.

![SQLlib](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/ca7a1b81-d50d-4486-b928-27c837abec8d)
![VBAUnitTester](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/ac91de93-84a7-4c0b-b148-7d96bb362eb2)
![WB_Test_SQL](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/fa988621-9e0e-4144-94b3-59952da44522)
![Error_SQLlibTests](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/5870503e-79d8-41db-8091-f900d46f31a6)

**Comment by Beakerboy** [comment]
After making the xlam, Did you enable the addin within excel?

**Comment by Beakerboy** [comment]
It looks like a class is missing. There needs to be a class that implements iTestableInterface.

**Comment by Beakerboy** [comment]
I created a new branch called missing_file. I copied and pasted some code from another project into the missing file and modified to where it should work.

**Comment by Beakerboy** [comment]
I found a couple other small bugs in the testing, but it all imports and works on my end. I also figured out the "correct" way to handle files with CRLF line endings in git, so hopefully that is an issues that will not come back. Please let me know that the missing_file branch fixes this issue.

**Comment by Beakerboy** [comment]
I'm going to close this since I merged the fixes into the dev branch. Please reopen if the latest dev branch does not resolve your problems.

**Comment by LightMike** [comment]
Hello Kevin - I am back in debugging.
So far I am a purely procedural programmer in VBA and picked your project to
learn about OOP and classes in VBA.
As you probably recognised I have not installed a VBA ID but working purely in Excel VBA.
(sorry I am not familiar with GitHub and pull-request issues)

What I did now:
- loaded the zip file "VBA-Unit-Tester-main.zip" again
- extracted to a new folder
- opened all classes and modules with editor --> CR LF all ok now
- created VBAUnitTester.xlsm
- added classes and modules from src by drag and drop --> all fine
- renamed VBAProject to VBAUnitTester
- saved as VBAUnitTester.xlam
- closed VBAUnitTester.xlsm

- created new Test_SQL_Classes.xlsm
- checked and addes all modules and classes from testing --> all fine
- renamed the project TestSQLClasses_XLSM
- enabled: SQLlib.xlam
- enabled: VBAUnitTester.xlam
- typed "=RunTests()" in cell A1
- this time I got a bit further but then...
- 
![Error_CreateTestCase](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/5c183950-a27b-4c70-859b-fc6a6bed4c9e)
![ProjAndAddIns](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/a935331e-cd85-4e7c-8136-c9a5296e2fa5)

**Comment by Beakerboy** [comment]
@LightMike I’m happy to help! I also do not have an IDE outside the studio that ships with MS Office. 
i think the last thing you need to do is import the test addin into the active sheet. Open Microsoft Visual Basic for Applications and select Tools>References, then check the box next to VBAUnitTester. This will make sure the active sheet knows that CreateTestCase() means VBAUnitTester.CreateTestCase()

**Comment by LightMike** [comment]
Sorry. Still same error.
Where could I find the "CreateTestCase()"??
Should it be 
--> Function CreateTestRunner()??



![ws_addIns](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/c2bcbe28-9c77-40d7-9296-989ac5ab3d89)
![VBA_Reference](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/40e430b5-0715-46aa-a1a5-db6551107ac3)

**Comment by Beakerboy** [comment]
Arg….another missing file. I just added “Modules/UnitTesterFactory.bas” to the Vba-Unit-Tester project, and deleted the older factory module.

**Comment by LightMike** [comment]
Hello,
download both files.
VBA_assertions
UnitTesterFactory

![NewVBAUnitTester](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/823f2a3d-2b77-4a2e-8edf-e0ee11fb8416)
![NewError](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/159ec328-26d1-4632-8031-fdac0d2046fd)

**Comment by Beakerboy** [comment]
Maybe change it to

```

Function CreateTestRunner()
    Set Runner = New TestRunner
    Runner.Initialize
    Set CreateTestRunner = Runner
End Function

Function CreateTestCase()
    Set CreateTestCase = New TestCase
End Function
```

I just checked my copy and it runs fine the way it was originally written. I used Google translate on the error and it said the keyword “New” was used incorrectly, and this version works too. Let me know if my translation of the error in not right. I wonder if Google can help, because, like I said It works fine for me.

**Comment by LightMike** [comment]
Nope. Still getting the error that I cannot create a New TestRunner

![TestRunnerNew_Error](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/6ef026a1-8fb2-4850-84eb-7341b2e1a036)

**Comment by Beakerboy** [comment]
If you have a ClassModule named TestRunner, and you are calling `New TestRunner` from within the same library, it should be working. Is this call coming from within VBAUnitTester, or SqlTest?

Excel is set up such that if a class is public, you cannot instantiate it from outside the library. The way around this is to write a factory method inside a standard module, in the library. Any external code then calls this factory method. One of these cases must not be met. Either the factory method is outside a module, or the module is outside the library.

Make sure the TestRunner classmodule is “publicNotCeatable”. This error might be able to pop up if it is set to ‘private’. If the module code was imported (vs copy paste) that attribute should have been automatically set.

**Comment by LightMike** [comment]
You are right. The call is coming from outside VBAUnitTester.xlam
But where to put the Modules and ClassModules that are placed in: VBA-Unit-Tester/testing

**Comment by Beakerboy** [comment]
Do you want to test the tester, or test SQLlib?

To test an addin you create and enable the addin, then make a new spreadsheet with the testing code. if your personal goal is to learn to program Object Oriented VBA, I’d suggest using the library over testing it. Even better, implement a feature, like a SQL_Create enhancement that is listed in the issues queue. Writing new tests would be good practice too, but it’s certainly several more layers deep.

It should work if both the Unit-Tester src and Unit-Tester tests are all in one xlsm or xlam file too. For distribution, it’s usually recommend to not ship testing code with production code, hence the separation.

**Comment by LightMike** [comment]
Hello,
when looking for a project to learn from, I liked the idea to have an excel interface to SQL.
I wanted to make sure that the SQLlib.xlam is working properly. Therefore I also tried with the
VBAUnitTester, because I thought this is a smart idea.
I thought once I am sure that the code works fine I can start to work through the classes and interfaces 
and learn, what you did.
Unfortunately I ran into the problems described and do not understand how this could work on your side
but not on mine.

Status. As written above I have:

VBAUnitTester.xlam
SQLlib.xlam
each with the classes and modules from the corresponding src directory only.
Screenshots above.

Created New File: Test_SQL_Classes.xlsm
added all modules and classes from the 
VBA-Unit-Tester\testing directory
![TestSQLClasses](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/6a90f095-95e0-4ebe-a3cc-a96e5cc2a36e)


enabled: 
SQLlib.xlam
VBAUnitTester.xlam

In TestSQLClasses_XLSM (Test_SQL_Classes.xlsm)
typed "=RunTests()" in cell A1
or start the function 
Public Function RunTests() in the VBA window

stepping through the code:

TestConfig.Run --> UnitTesterTestConfig --> Public Function iTestableProject_Run()
Configure --> Private Sub Configure()
Set TestRunner = CreateTestRunner() --> Module TestRunnerFactory

and here it is stuck since the TestRunner class is in VBAUnitTester.xlam
![image](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/28efd2ee-c092-43a1-9377-eb82ba31c9b0)

**Comment by LightMike** [comment]
What I understood is the idea to have an xlam and to call the classes from an excel file referencing the xlam. But if I cannot instanciate TestRunner from TestSQLClasses_XLSM (Test_SQL_Classes.xlsm). It will probably also not work to create classes in SQLlib.xlam. Am I right in these thoughts??

**Comment by Beakerboy** [comment]
If you want to test the SQLlib project, you need to use the files in the VBA-SQL-Library/testing directory. The files in VBA-Unit-Tester/testing are to test the tester itself.

Edit. The TestRunnerFactory does not belong there. Delete it. If you want to test SQLlib, use only these files:
https://github.com/Beakerboy/VBA-SQL-Library/tree/master/testing

you somehow have a mix of files from the VBAUnitTester/src VBAUnitTester/testing and SQLlib/testing….actually, there is no module named SQLTester anywhere, did you make that one up?

**Comment by LightMike** [comment]
Just to be sure:
SQLlib.xlam
plus VBAUnitTester_TestSQLlib.xlsm with modules
VBA-Unit-Tester/src
VBA-SQL-Library/testing
![TestSQL_Lib](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/b76a359b-5aa9-4644-bf1e-e94f8a4cfe39)
![TestSQLlib_Error ](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/9ff178fe-12be-41b8-b153-be4cb0e1a2e4)

SQLlibTests is unknown userdefined type
where to get SQlTester from??

**Comment by Beakerboy** [comment]
If you want to test SQLlib, use **ONLY** these files:
https://github.com/Beakerboy/VBA-SQL-Library/tree/master/testing

Why do you have TestCase, TestRunner and TestReporter in there? The SQLlibTests file [is in the repository](https://github.com/Beakerboy/VBA-SQL-Library/blob/master/testing/ClassModules/SQLlibTests.cls)

Again...to test the SQLlib project, you will need to:
* Install the SQLlib addin.
* Install the VbaUnitTester addin
* Import the files from SQLlib/testing into an .xlsm file
* Add the Reference to VBAUnitTester and SQLLib to the SQLLib/testing project
* RunTests()

Combining the SQLlib/testing and the VbaUnitTester/src code in one project might work. (crossing fingers)

**Comment by LightMike** [comment]
Hello Kevin,
thanks again. My usual procedure for download from GitHub is dowloading the zip file, extracting,
then importing to excel vba by drag and drop.
Thought I selected all files from /testing/ClassModules - SQLlibTests.cls did not import and I did not 
recognize. Drag and drop the file alone worked.

**Comment by LightMike** [comment]
Module SQLRecordset

Public Property iSQLRecordset_EOF()
    iSQLRecordset_EOF = orst.EOF
End Function

Changed it to Puclic Function. Correct?

**Comment by LightMike** [comment]
Still getting Error in Module SQLTestRecordset:
![Err_SQLRecordset](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/76d64595-e7a1-435d-b858-95df120280e9)

**Comment by Beakerboy** [comment]
> Module SQLRecordset
> 
> Public Property iSQLRecordset_EOF() iSQLRecordset_EOF = orst.EOF End Function
> 
> Changed it to Puclic Function. Correct?

That was updated In the repo last week:

```vba
' Property: EOF
Property Get EOF()

End Property
```

**Comment by LightMike** [comment]
the one I used is dated 1st Nov 2023

**Comment by LightMike** [comment]
it is the classmodule SQLTestRecordset.cls not the interface iSQLRecordset.cls
it is asking for an implementation of GetRows from the interface ISQLRecordset.cls

' Function: GetValue
Public Function GetRows(num As Integer)

End Function

**Comment by Beakerboy** [comment]
SQLTestRecordset is a Classmodule which includes the code needed to test the SQLRecordset ClassModule. I may have found that and updated it last week as well:

```vba
Public Function iSQLRecordset_GetRows(num As Integer)
    iSQLRecordset_GetRows = num
End Function
```

In case you don’t know, an Interface defines the minimum required set of methods needed by a class to fulfill the requirements of the interface. The Interface only defines the methods, but does not supply any implementation details. All the actual code is in the class. Since SQLTestRecordset.cls has code, it cannot be an Interface.

**Comment by LightMike** [comment]
Is this also fixed?? Module TestCase:
![Err_GetObjectFunctions](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/a69e47f4-36e1-4755-bda3-577861b5ebe0)

**Comment by Beakerboy** [comment]
Yes, there is one more file missing from the repository. I didn’t think I had started using it yet. I’ll upload it this weekend.

**Comment by Beakerboy** [comment]
I've added the last missing file:
https://github.com/Beakerboy/VBA-Unit-Tester/blob/main/src/Modules/ObjectIntrospection.bas

**Comment by LightMike** [comment]
Hello Kevin.
Thank youj for adding the code.

So I started over again

- Create the SQLlib addin.
- Create the VbaUnitTester addin
- Install the SQLlib addin.
- Install the VbaUnitTester addin
- Import the files from SQLlib/testing into an .xlsm file
- Add the Reference to VBAUnitTester and SQLLib to the SQLLib/testing project
- RunTests()

There is apparently one typo left in
SQLlib SQLDatabase.cls

    'rst.OpenwsRecordset sSQL, cnt              'Execute the query
    rst.OpenRecordset sSQL, cnt              'Execute the query

after correcting this all tests run fine.

![Test_Result](https://github.com/Beakerboy/VBA-SQL-Library/assets/71723869/22cb47ba-d37a-4d04-8795-4ea0f862e8e9)

**Comment by LightMike** [comment]
Next task will be to connect to a mySQL DB on https://www.db4free.net/

**Comment by Beakerboy** [comment]
Let me know how it works! I’ve used it with PostgreSQL and MS SqlServer…and maybe a little MySQL. One user had some issues with Access.
